use constraints;

SELECT * FROM STUDENT;
SELECT * FROM VOTE

DELIMITER //
CREATE TRIGGER STUDENT_AFTER_UPDATE_TRIGGER
AFTER UPDATE ON STUDENT FOR EACH ROW
BEGIN
	IF NEW.AGE>=18 THEN
		UPDATE  VOTE SET AGE=NEW.AGE WHERE VOTER_ID=NEW.REGNO;
		IF row_count()=0 THEN
			INSERT INTO VOTE( VOTER_ID,VOTER_NAME,AGE) VALUES(NEW.REGNO,NEW.STUDENT_NAME,NEW.AGE);
		END IF;
    END IF;
END;
//

UPDATE STUDENT SET AGE=18 WHERE REGNO=1001;
UPDATE STUDENT SET AGE=21 WHERE REGNO=1002;