use constraints;

SELECT * FROM STUDENT;
SELECT * FROM VOTE

DELIMITER //
CREATE TRIGGER STUDENT_BEFORE_UPDATE_TRIGGER
BEFORE UPDATE ON STUDENT FOR EACH ROW
BEGIN
	IF (NEW.AGE>=18) THEN
		UPDATE  VOTE SET AGE=NEW.AGE WHERE VOTER_ID=NEW.REGNO;
	ELSEIF(NEW.AGE<18) THEN
		DELETE FROM VOTE WHERE VOTER_ID=NEW.REGNO;
	END IF;
END;
//

UPDATE STUDENT SET AGE=17 WHERE REGNO=1001;
UPDATE STUDENT SET AGE=18 WHERE REGNO=1002;