use constraints;

SELECT * FROM EMPLOYEE;

DELIMITER //
CREATE TRIGGER EMPLOYEE_BEFORE_INSERT_TRIGGER
BEFORE INSERT ON EMPLOYEE FOR EACH ROW
BEGIN
	IF NEW.DOJ IS NULL THEN
		SET NEW.DOJ=NOW();
	END IF;
END;
//

INSERT INTO EMPLOYEE (EMPID,EMPNAME) VALUES(1004,'JK');
INSERT INTO EMPLOYEE (EMPID,EMPNAME) VALUES(1005,'RANI');
INSERT INTO EMPLOYEE (EMPID,EMPNAME,DOJ) VALUES(1006,'SENTHIL','2023-09-01 09:05:56');

DROP TRIGGER EMPLOYEE_BEFORE_INSERT_TRIGGER;