CREATE DATABASE CD5;
USE CD5;

CREATE TABLE EMPLOYEE(EMPLOYEE_ID INT ,FIRST_NAME VARCHAR(100),LAST_NAME VARCHAR(100),SALARY INT,
JOINING_DATE VARCHAR(100),DEPARTMENT VARCHAR(100));

DESCRIBE EMPLOYEE;

CREATE TABLE INCENTIVES(EMPLOYEE_REF_ID INT,INCENTIVE_DATE VARCHAR(100),INCENTIVE_AMOUNT INT);

DESCRIBE INCENTIVES;

INSERT INTO EMPLOYEE VALUES(1,'JOHN','ABRAHAM',1000000,'2013-01-01 12.00.00','BANKING');
INSERT INTO EMPLOYEE VALUES(2,'MICHAEL','CLARKE',800000,'2013-01-01 12.00.00','INSURANCE');
INSERT INTO EMPLOYEE VALUES(3,'ROY','THOMAS',700000,'2013-01-01 12.00.00','BANKING');
INSERT INTO EMPLOYEE VALUES(4,'TOM','JOSE',600000,'2013-01-01 12.00.00','INSURANCE');
INSERT INTO EMPLOYEE VALUES(5,'JERRY','PINTO',650000,'2013-01-01 12.00.00','INSURANCE');
INSERT INTO EMPLOYEE VALUES(6,'PHILIP','MATHEW',750000,'2013-01-01 12.00.00','SERVICES');
INSERT INTO EMPLOYEE VALUES(7,'TOWINO','THOMAS',650000,'2013-01-01 12.00.00','SERVICES');
INSERT INTO EMPLOYEE VALUES(8,'JEFFIN','JOSE',600000,'2013-01-01 12.00.00','INSURANCE');

INSERT INTO INCENTIVES VALUES(1,'2013-02-01',5000);
INSERT INTO INCENTIVES VALUES(2,'2013-02-01',3000);
INSERT INTO INCENTIVES VALUES(3,'2013-02-01',4000);
INSERT INTO INCENTIVES VALUES(4,'2013-01-01',4500);
INSERT INTO INCENTIVES VALUES(5,'2013-01-01',3500);
 
 DROP TABLE  EMPLOYEE;
 DROP TABLE INCENTIVES;
 
 -- ANSWER---
 
SELECT * FROM EMPLOYEE;

SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEE;

SELECT UPPER(FIRST_NAME)  FROM EMPLOYEE;

SELECT LOWER(FIRST_NAME)  FROM EMPLOYEE;

SELECT DISTINCT DEPARTMENT FROM EMPLOYEE;

SELECT LEFT(FIRST_NAME,3) FROM EMPLOYEE;

SELECT POSITION('O' IN FIRST_NAME) AS POSITION_OF_O FROM EMPLOYEE WHERE FIRST_NAME='JOHN';

SELECT RTRIM(FIRST_NAME) FROM EMPLOYEE;

SELECT LTRIM(FIRST_NAME) FROM EMPLOYEE;

SELECT LENGTH(FIRST_NAME) FROM EMPLOYEE;

SELECT REPLACE(FIRST_NAME,'O','$') FROM EMPLOYEE;

SELECT CONCAT(FIRST_NAME,'_',LAST_NAME) FROM EMPLOYEE;

SELECT FIRST_NAME,YEAR(JOINING_DATE),MONTH(JOINING_DATE),DAY(JOINING_DATE) FROM EMPLOYEE;

SELECT  * FROM EMPLOYEE  ORDER BY  FIRST_NAME ASC;

SELECT  * FROM EMPLOYEE  ORDER BY  FIRST_NAME DESC;

SELECT  * FROM EMPLOYEE  ORDER BY  FIRST_NAME ASC,SALARY DESC;

SELECT * FROM EMPLOYEE WHERE FIRST_NAME='JOHN';

SELECT * FROM EMPLOYEE WHERE FIRST_NAME IN ('JOHN','ROY');

SELECT * FROM EMPLOYEE WHERE FIRST_NAME NOT IN ('JOHN','ROY');

SELECT * FROM EMPLOYEE WHERE LENGTH(First_Name) = 4 AND RIGHT(First_Name, 1) = 'N';

SELECT * FROM EMPLOYEE WHERE LENGTH(First_Name) = 4 AND LEFT(First_Name, 1) = 'J';

SELECT * FROM EMPLOYEE WHERE SALARY > 600000;

SELECT * FROM EMPLOYEE WHERE SALARY < 800000;

SELECT * FROM EMPLOYEE WHERE SALARY BETWEEN 500000 AND 800000;

SELECT * FROM EMPLOYEE WHERE FIRST_NAME IN ('JOHN','MICHAEL');

SELECT * FROM EMPLOYEE WHERE YEAR(JOINING_DATE)=2013;

SELECT * FROM EMPLOYEE WHERE MONTH(JOINING_DATE)=01;

SELECT * FROM EMPLOYEE WHERE JOINING_DATE < '2013-01-01';

SELECT * FROM EMPLOYEE WHERE JOINING_DATE > '2013-01-31';

SELECT JOINING_DATE FROM EMPLOYEE;

SELECT TIME_FORMAT(JOINING_DATE,'%H:%I:%S:%f') FROM EMPLOYEE;

SELECT DATEDIFF(JOINING_DATE,INCENTIVE_DATE) FROM EMPLOYEE,INCENTIVES;

select CURRENT_DATE();

SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEE WHERE LAST_NAME LIKE '%\\%%';

SELECT REPLACE(LAST_NAME,'%',' ')  FROM EMPLOYEE;

SELECT DEPARTMENT ,AVG(SALARY) AS AVERAGE_SALARY FROM EMPLOYEE
 GROUP BY DEPARTMENT ORDER BY AVERAGE_SALARY ASC;
 
SELECT DEPARTMENT ,MAX(SALARY) AS MAXIMUM_SALARY FROM EMPLOYEE
 GROUP BY DEPARTMENT ORDER BY MAXIMUM_SALARY ASC;
 
SELECT DEPARTMENT ,MIN(SALARY) AS MINIMUM_SALARY FROM EMPLOYEE 
GROUP BY DEPARTMENT ORDER BY MINIMUM_SALARY ASC;

SELECT YEAR(JOINING_DATE) AS JOINING_YEAR,MONTH(JOINING_DATE)AS JOINING_MONTH,COUNT(*) AS NUM_OF_EMPLOYEE_JOINED
FROM EMPLOYEE GROUP BY YEAR(JOINING_DATE), MONTH(JOINING_DATE)ORDER BY JOINING_YEAR,JOINING_MONTH;

SELECT DEPARTMENT,SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEE GROUP BY DEPARTMENT
 HAVING SUM(SALARY)>800000 ORDER BY TOTAL_SALARY DESC;
 
SELECT E.FIRST_NAME,I.INCENTIVE_AMOUNT FROM EMPLOYEE E INNER JOIN INCENTIVES  I ON 
E.EMPLOYEE_ID=I.EMPLOYEE_REF_ID; 

SELECT E.FIRST_NAME,I.INCENTIVE_AMOUNT FROM EMPLOYEE E INNER JOIN INCENTIVES  I ON 
E.EMPLOYEE_ID=I.EMPLOYEE_REF_ID WHERE I.INCENTIVE_AMOUNT>3000; 

SELECT E.FIRST_NAME,I.INCENTIVE_AMOUNT FROM EMPLOYEE E LEFT JOIN INCENTIVES  I ON 
E.EMPLOYEE_ID=I.EMPLOYEE_REF_ID; 

SELECT E.FIRST_NAME,COALESCE(I.INCENTIVE_AMOUNT,'0') FROM EMPLOYEE E RIGHT JOIN INCENTIVES  I ON 
E.EMPLOYEE_ID=I.EMPLOYEE_REF_ID; 

SELECT FIRST_NAME,(SELECT COALESCE(MAX(INCENTIVE_AMOUNT),0) FROM INCENTIVES
 WHERE EMPLOYEE_REF_ID=EMPLOYEE_ID) FROM EMPLOYEE;

SELECT  SALARY FROM EMPLOYEE  ORDER BY SALARY DESC LIMIT 2;

SELECT  SALARY FROM EMPLOYEE  ORDER BY SALARY DESC LIMIT 1 OFFSET 1;

SELECT FIRST_NAME FROM EMPLOYEE
UNION 
SELECT LAST_NAME FROM EMPLOYEE;

SELECT * FROM EMPLOYEE E INNER JOIN INCENTIVES I ON E.EMPLOYEE_ID=I.EMPLOYEE_REF_ID;

SELECT FIRST_NAME,SALARY ,
CASE
	WHEN FIRST_NAME='JOHN' THEN SALARY * 0.20
    WHEN FIRST_NAME='ROY' THEN SALARY * 0.10
    ELSE SALARY * 0.15
END FROM EMPLOYEE;

SELECT DEPARTMENT,
CASE 
	WHEN DEPARTMENT='BANKING' THEN 'Bank Dept'
    WHEN DEPARTMENT='INSURANCE' THEN 'Insurance Dept'
    WHEN DEPARTMENT='SERVICES' THEN 'Services Dept'
    ELSE DEPARTMENT
END FROM EMPLOYEE;

SET SQL_SAFE_UPDATES=0;
DELETE FROM EMPLOYEE WHERE EMPLOYEE_ID  IN(SELECT EMPLOYEE_REF_ID FROM INCENTIVES); 

INSERT INTO EMPLOYEE(LAST_NAME) VALUES("'");

UPDATE INCENTIVES  SET INCENTIVE_AMOUNT='13000' 
WHERE EMPLOYEE_REF_ID=(SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE FIRST_NAME='JOHN');
