use constraints;

SELECT * FROM orders;
select * from customer;

SELECT ORDERID,ORDERS.CUSTOMERID,CUSTOMERNAME,ITEM,ORDERDATE /* USE JOIN 0R INNER JOIN*/
FROM ORDERS INNER JOIN CUSTOMER ON ORDERS.CUSTOMERID=CUSTOMER.CUSTOMERID;

SELECT ORDERID,ORDERS.CUSTOMERID /* ORDERS TABLE*/,CUSTOMERNAME,ITEM,ORDERDATE 
FROM ORDERS LEFT JOIN CUSTOMER ON ORDERS.CUSTOMERID=CUSTOMER.CUSTOMERID;

SELECT ORDERID,CUSTOMER.CUSTOMERID /* CUSTOMER TABLE*/,CUSTOMERNAME,ITEM,ORDERDATE 
FROM ORDERS LEFT JOIN CUSTOMER ON ORDERS.CUSTOMERID=CUSTOMER.CUSTOMERID;

SELECT ORDERID,ORDERS.CUSTOMERID /* ORDERS TABLE*/,CUSTOMERNAME,ITEM,ORDERDATE 
FROM ORDERS RIGHT JOIN CUSTOMER ON ORDERS.CUSTOMERID=CUSTOMER.CUSTOMERID;

SELECT ORDERID,ORDERS.CUSTOMERID /* ORDERS TABLE*/,CUSTOMERNAME,ITEM,ORDERDATE,CITY,STATE,COUNTRY 
FROM ORDERS RIGHT JOIN CUSTOMER ON ORDERS.CUSTOMERID=CUSTOMER.CUSTOMERID;


SELECT ORDERID,ORDERS.CUSTOMERID /* ORDERS TABLE*/,CUSTOMERNAME,ITEM,ORDERDATE 
FROM ORDERS LEFT JOIN CUSTOMER ON ORDERS.CUSTOMERID=CUSTOMER.CUSTOMERID
UNION /* FULL OUTER JOIN NOT IN MYSQL BUT OTHERSQL HAVE SO WE USE UNION*/
SELECT ORDERID,ORDERS.CUSTOMERID /* ORDERS TABLE*/,CUSTOMERNAME,ITEM,ORDERDATE 
FROM ORDERS RIGHT JOIN CUSTOMER ON ORDERS.CUSTOMERID=CUSTOMER.CUSTOMERID;

-- SELF JOIN--
SELECT C1.CUSTOMERID,C1.CUSTOMERNAME,C1.ADDRESS,C1.CITY,C1.POSTALCODE,C1.STATE,C1.COUNTRY FROM CUSTOMER C1,CUSTOMER C2
WHERE C1.CUSTOMERID=C2.CUSTOMERID;

-- CROSS JOIN--
SELECT ORDERID,ORDERS.CUSTOMERID /* ORDERS TABLE*/,CUSTOMERNAME,ITEM,ORDERDATE 
FROM ORDERS CROSS JOIN CUSTOMER;

-- MYSQL ALIAS--
SELECT ORDERID,t1.CUSTOMERID,CUSTOMERNAME,ITEM,ORDERDATE /* USE JOIN 0R INNER JOIN*/
FROM ORDERS t1 INNER JOIN CUSTOMER t2 ON t1.CUSTOMERID=t2.CUSTOMERID;