CREATE DATABASE CD7;
USE CD7;

CREATE TABLE EMPLOYEE( ID INT AUTO_INCREMENT PRIMARY KEY,NAME VARCHAR(100),PASSWORD VARCHAR(100),EMAIL VARCHAR(50),COUNTRY VARCHAR(100));

INSERT INTO EMPLOYEE (NAME, PASSWORD, EMAIL, COUNTRY)
VALUES ('AJAY KUMAR', '123456@AJAY', 'AJAY18@GMAIL.COM', 'INDIA');

INSERT INTO EMPLOYEE (NAME, PASSWORD, EMAIL, COUNTRY)
VALUES ('SAM', '1234/SAM', 'SAM3@GMAIL.COM', 'USA');

INSERT INTO EMPLOYEE (NAME, PASSWORD, EMAIL, COUNTRY)
VALUES ('KURZ', 'KURZ@+09', 'KURZA@GMAIL.COM', 'RUSSIA');

